# Generated by Django 5.2.7 on 2025-10-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_user_usn_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
