# Generated by Django 5.2.7 on 2025-12-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='memberlog',
            name='member',
        ),
        migrations.AddField(
            model_name='memberlog',
            name='member_email',
            field=models.EmailField(blank=True, default='-', max_length=254),
        ),
        migrations.AddField(
            model_name='memberlog',
            name='member_role',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='memberlog',
            name='member_unique_id',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='memberlog',
            name='member_username',
            field=models.CharField(blank=True, default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='memberlog',
            name='performed_by',
            field=models.CharField(max_length=150),
        ),
    ]
