"""
Django settings for ilas_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY", "unsafe-dev-secret-key")

DEBUG = os.environ.get("DEBUG", "False") == "True"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_RESOURCE_POLICY = "same-origin"
SECURE_REFERRER_POLICY = "same-origin"


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',


    # Local apps
    'core',
    'library',
    'library.barcode',
    'accounts',
    'django_celery_results',
    'django_celery_beat',  # optional, for scheduled tasks

    'django_filters',



]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ilas_backend.urls'
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
       "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}


# JWT Settings (optional tweak)
from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # ✅ must include this line
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = 'ilas_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url


DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # ✅ Indian timezone for logs

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
    ]
else:
    CORS_ALLOWED_ORIGINS = [
        "https://ilas.vercel.app",
    ]


CORS_ALLOW_CREDENTIALS = False

CORS_ALLOW_HEADERS = ["authorization","content-type","accept","origin","x-requested-with",]

CORS_EXPOSE_HEADERS = [
    "Content-Type",
    "Content-Disposition",
    "Authorization",
]

# ----------------------------------------------------------
# 📦 MEDIA FILE CONFIGURATION (for uploaded images & barcodes)
# ----------------------------------------------------------

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
LIBRARY_BORROW_DAYS_DEFAULT = 14
LIBRARY_FINE_PER_DAY = "1.00"
LIBRARY_GRACE_DAYS = 0
LIBRARY_MAX_FINE = None
LIBRARY_MAX_ACTIVE_LOANS = 5
DEFAULT_BOOK_COVER = "defaults/default_book_cover.jpg"  # optional


# ================================================================
# 📧 EMAIL CONFIGURATION (DEV + PROD READY)
# ================================================================

# Environment variable to control mode (set this in Railway)
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

if ENVIRONMENT == "production":
# ✅ Real email sending (using Gmail App Password)
# ================================
# 📧 Gmail SMTP Configuration
# ================================
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = "ilasdrait@gmail.com"
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

else:
    # 🧪 Development mode (no real emails)
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "noreply@ilas.local"

# Optional (good for debugging email sending)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"django.core.mail": {"handlers": ["console"], "level": "DEBUG"}},
}



# Uncomment later if you move to cloud storage:
# DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# -------------------------------------------------
# ⚙️ Celery + Redis Configuration (OPTIONAL)
# -------------------------------------------------

USE_CELERY = os.getenv("USE_CELERY", "False") == "True"

if USE_CELERY:
    from celery.schedules import crontab

    CELERY_BROKER_URL = os.environ.get(
        "CELERY_BROKER_URL", "redis://127.0.0.1:6379/0"
    )
    CELERY_RESULT_BACKEND = CELERY_BROKER_URL
    CELERY_ACCEPT_CONTENT = ["json"]
    CELERY_TASK_SERIALIZER = "json"
    CELERY_RESULT_SERIALIZER = "json"
    CELERY_TIMEZONE = "Asia/Kolkata"
    CELERY_TASK_TRACK_STARTED = True
    CELERY_TASK_TIME_LIMIT = 30 * 60

    # -------------------------------------------------
    # Celery Beat Schedule (only when Celery is enabled)
    # -------------------------------------------------
    CELERY_BEAT_SCHEDULE = {
        "archive-old-transactions-weekly": {
            "task": "library.tasks.archive_old_transactions",
            "schedule": crontab(day_of_week="sun", hour=1, minute=0),
        },
        "cleanup-orphan-barcodes-weekly": {
            "task": "library.tasks.cleanup_orphan_barcodes",
            "schedule": crontab(day_of_week="sun", hour=2, minute=0),
        },
    }



SPECTACULAR_SETTINGS = {
    "TITLE": "ILAS Library Management API",
    "DESCRIPTION": "Comprehensive API documentation for ILAS (Innovative Library Automation System)",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CONTACT": {"name": "ILAS Dev Team", "email": "support@ilas-system.local"},
    "LICENSE": {"name": "MIT License"},
    "SCHEMA_PATH_PREFIX": r"/api/v1/",
    "SCHEMA_COERCE_PATH_PK_SUFFIX": True,  # auto-detects primary key params
    "COMPONENT_SPLIT_REQUEST": True,        # separates input/output schemas
    "SORT_OPERATIONS": True,                # keeps endpoints alphabetical
    "SORT_OPERATIONS_ALPHABETICALLY": True,
    "POSTPROCESSING_HOOKS": [],             # optional custom cleanup
}

REST_FRAMEWORK.update({
    "DEFAULT_THROTTLE_CLASSES": ["rest_framework.throttling.ScopedRateThrottle"],
    "DEFAULT_THROTTLE_RATES": {
        "docs": "5/min",
        "reports": "10/min",
    },
})


STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ALLOWED_HOSTS = [
    "ilas-production.up.railway.app",
    "localhost",
    "127.0.0.1",
    "ilas.vercel.app",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
    "https://ilas-production.up.railway.app",
    "https://ilas.vercel.app",

]


CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
